spring.application.name=loginPage

spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://dpg-d8gmcdbbc2fs73eof3ng-a.virginia-postgres.render.com:5432/loginpage_mrk7
spring.datasource.username=loginpage_mrk7_user
spring.datasource.password=3dkEYfZF4buKnGcTYzuFI55zV8YDkkDF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


